# Generated by Django 5.0.1 on 2024-02-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
